# Generated by Django 5.1.6 on 2025-02-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('loss', models.FloatField()),
                ('brand', models.CharField(max_length=3, null=True)),
                ('epoch_brand', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metricas',
                'ordering': ['-created'],
            },
        ),
    ]
