# Generated by Django 5.1.6 on 2025-02-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigatokaDetectionSystem', '0002_analityc_metric_folds_alter_metric_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confusion_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('support', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Confusion_Matrix',
                'verbose_name_plural': 'Matriz de Confusion',
                'ordering': ['-created'],
            },
        ),
    ]
